name: better_jwk
version: 1.0.0
homepage: https://github.com/tjcampanella/better_cryptography
description: JWK (JSON Web Key) encoding and decoding (for package:better_cryptography).

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  better_cryptography: ^1.0.0+1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.0
