name: better_cryptography
version: 1.0.0
homepage: https://github.com/tjcampanella/better_cryptography
description:
  Cryptographic algorithms for encryption, digital signatures, key agreement, authentication, and
  hashing. AES, Chacha20, ED25519, X25519, and more. Web Crypto support.

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  fixnum: ^1.0.0
  js: ^0.6.3
  meta: ^1.3.0
  typed_data: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.0
