name: better_cryptography_flutter
description:
  A version of 'package:better_cryptography' that speeds up asynchronous invocations with native APIs of
  Android, iOS, and Mac OS X.
version: 1.0.0
homepage: https://github.com/tjcampanella/better_cryptography

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  better_cryptography: ^1.0.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: tjcampanella.better_cryptography_flutter
        pluginClass: CryptographyFlutterPlugin
      ios:
        pluginClass: CryptographyFlutterPlugin
      macos:
        pluginClass: CryptographyFlutterPlugin
