name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [2.17.0, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies (better_cryptography)
        working-directory: better_cryptography
        run: dart pub get

      - name: Install dependencies (better_jwk)
        working-directory: better_jwk
        run: dart pub get

      - name: Run tests (better_cryptography)
        working-directory: better_cryptography
        run: dart test --platform=vm

      - name: Run tests (better_jwk)
        working-directory: better_jwk
        run: dart test --platform=vm
